CREATE FUNCTION region ("value" TEXT)
    RETURNS BOOLEAN
AS $$
BEGIN
    RETURN ("value" ~* '^[A-Z]{2}$');
END
$$
    LANGUAGE plpgsql
    IMMUTABLE
    RETURNS NULL ON NULL INPUT;

COMMENT ON FUNCTION region (TEXT) IS 'ISO 3166-1';
